project: https://github.com/AudioReach/audioreach-audio-utils

branches:
  main:
    modes:
      blocking:
        headers:
          - audio-route/include/system/*.h
          - audio-route/include/audio_route/*.h
